# -*- coding: utf-8 -*-
"""tax_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbEq0JldAIHQQSw1IgBkUjmSxocB8fYh
"""

# ================= ADVANCED TAX OPTIMIZATION SYSTEM (INDIA) ================= #

# ---------------- MERGE SORT ---------------- #
def merge_sort(arr):
    if len(arr) <= 1:
        return arr
    mid = len(arr)//2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i]['priority'] < right[j]['priority']:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])
    return result


# ---------------- TAX SLABS ---------------- #
OLD_REGIME = [
    {'limit': 250000, 'rate': 0},
    {'limit': 500000, 'rate': 0.05},
    {'limit': 1000000, 'rate': 0.20},
    {'limit': float('inf'), 'rate': 0.30}
]

NEW_REGIME = [
    {'limit': 300000, 'rate': 0},
    {'limit': 600000, 'rate': 0.05},
    {'limit': 900000, 'rate': 0.10},
    {'limit': 1200000, 'rate': 0.15},
    {'limit': 1500000, 'rate': 0.20},
    {'limit': float('inf'), 'rate': 0.30}
]


# ---------------- SALARY ---------------- #
def get_salary():
    print("\n📊 Enter Salary Details")
    basic = float(input("Basic Salary: ₹"))
    hra = float(input("HRA Received: ₹"))
    other = float(input("Other Allowances: ₹"))
    bonus = float(input("Bonus: ₹"))

    gross = basic + hra + other + bonus
    return basic, hra, gross


# ---------------- HRA ---------------- #
def calculate_hra(basic, hra):
    rent = float(input("Annual Rent Paid: ₹"))
    city = input("Metro city? (yes/no): ").lower()

    percent = 0.5 if city == "yes" else 0.4

    hra_exemption = min(
        hra,
        rent - 0.1 * basic,
        percent * basic
    )

    hra_exemption = max(0, hra_exemption)

    print(f"HRA Exemption: ₹{hra_exemption}")
    return hra_exemption


# ---------------- PROPERTY ---------------- #
def property_details():
    print("\n🏠 Property Details")
    owns = input("Do you own property? (yes/no): ").lower()

    rental_income = 0
    interest = 0

    if owns == "yes":
        rented = input("Is it rented? (yes/no): ").lower()

        if rented == "yes":
            rental_income = float(input("Annual Rental Income: ₹"))

        interest = float(input("Home Loan Interest Paid: ₹"))

    return rental_income, interest


def apply_property(income, rental_income, interest):
    adjusted_rent = rental_income * 0.7  # 30% deduction
    interest_deduction = min(interest, 200000)

    income += adjusted_rent
    income -= interest_deduction

    print("\n🏠 Property Adjustment")
    print(f"Rental Income Added: ₹{adjusted_rent}")
    print(f"Interest Deduction: ₹{interest_deduction}")

    return income


# ---------------- DEDUCTIONS ---------------- #
DEDUCTIONS = [
    {'name': '80C', 'limit': 150000, 'priority': 1},
    {'name': '80D', 'limit': 25000, 'priority': 2},
    {'name': 'NPS', 'limit': 50000, 'priority': 0},
    {'name': 'Education Loan', 'limit': float('inf'), 'priority': 3},
    {'name': 'Donations', 'limit': float('inf'), 'priority': 4},
]


def get_deductions():
    print("\n💸 Enter Investments")
    investments = {}

    for d in DEDUCTIONS:
        try:
            amt = float(input(f"{d['name']} (max ₹{d['limit']}): "))
        except:
            amt = 0
        investments[d['name']] = amt

    return investments


def apply_deductions(income, investments):
    total = 0
    sorted_rules = merge_sort(DEDUCTIONS)

    print("\n[Applying Deductions]")

    for rule in sorted_rules:
        amt = investments.get(rule['name'], 0)
        claim = min(amt, rule['limit'])

        if claim > 0:
            total += claim
            print(f"{rule['name']}: ₹{claim}")

    if total == 0:
        print("(No deductions applied)")

    return total


# ---------------- TAX ---------------- #
def compute_tax(income, slabs):
    tax = 0
    prev = 0

    for slab in slabs:
        if income > slab['limit']:
            tax += (slab['limit'] - prev) * slab['rate']
            prev = slab['limit']
        else:
            tax += (income - prev) * slab['rate']
            break

    return tax


# ---------------- EXPENSE ---------------- #
def expense_analysis(income):
    print("\n📉 Monthly Expenses")

    try:
        rent = float(input("Rent: ₹"))
        food = float(input("Food: ₹"))
        travel = float(input("Travel: ₹"))
        emi = float(input("EMI: ₹"))
    except:
        rent = food = travel = emi = 0

    total = (rent + food + travel + emi) * 12
    savings = income - total

    print(f"Annual Expenses: ₹{total}")
    print(f"Estimated Savings: ₹{savings}")


# ---------------- SUGGESTIONS ---------------- #
def suggest(investments):
    print("\n💡 Tax Saving Suggestions")

    if sum(investments.values()) == 0:
        print("⚠️ No investments detected!")
        print("→ Invest in 80C (PPF, ELSS)")
        print("→ Use NPS for ₹50,000 extra deduction")
        print("→ Take Health Insurance (80D)")

    if investments.get('80C', 0) < 150000:
        print("→ Increase 80C investments")

    if investments.get('NPS', 0) < 50000:
        print("→ Invest more in NPS")

    if investments.get('80D', 0) < 25000:
        print("→ Get health insurance benefit")


# ---------------- MAIN ---------------- #
def main():
    print("\n💰 ADVANCED TAX OPTIMIZATION SYSTEM (INDIA)")

    basic, hra, gross = get_salary()
    hra_exemption = calculate_hra(basic, hra)

    rental_income, interest = property_details()

    investments = get_deductions()
    deduction_total = apply_deductions(gross, investments)

    # OLD REGIME
    taxable_old = gross - deduction_total - hra_exemption
    taxable_old = apply_property(taxable_old, rental_income, interest)

    # NEW REGIME
    taxable_new = gross

    tax_old = compute_tax(taxable_old, OLD_REGIME)
    tax_new = compute_tax(taxable_new, NEW_REGIME)

    print("\n========== RESULTS ==========")
    print(f"Old Regime Tax: ₹{tax_old}")
    print(f"New Regime Tax: ₹{tax_new}")

    if tax_old < tax_new:
        print("👉 Old Regime is Better")
    else:
        print("👉 New Regime is Better")

    expense_analysis(gross)
    suggest(investments)


# RUN
main()

